# Generated by Django 4.0.5 on 2022-07-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_price_arrivals_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivals',
            name='image',
        ),
        migrations.AddField(
            model_name='arrivals',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='arrivals',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
