# Generated by Django 4.0.5 on 2022-07-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_arrivals_image_arrivals_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('review', models.FloatField()),
                ('title', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
