# Generated by Django 4.0.5 on 2022-07-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
